name: School orange
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: school orange
    steps:
    - uses: actions/checkout@v2
    - id: school-orange
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'webchillgames'
        reponame: 'school-orange'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged